### ISSUE TITLE
📃:  Add 2048 Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [code-a2z/code-a2z#302]
:red_circle: **Title** : 2048 Game
:red_circle: **Aim** : Enhance engagement with 2048 integration.
:red_circle: **Tech Stack Used** : HTML, CSS, JAVASCRIPT

### Screenshots 📷
![webp_a76f3577-78e7-4fb9-9018-e11161475d2a](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/146121869/96e2b678-9d67-4599-9911-98ff51dd1945)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Asmita Mishra
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSoC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AsmitaMishra24 no games allowed.
